version: "3.7"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hellonet
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passu

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hellonet

networks:
  hellonet:
    driver: bridge
